# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8ab3e31a76e8302c3598d90b3db9d5cb"
name = "checknew"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_payment_customizations,write_orders,write_payment_customizations,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
