api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "cod-payment-logic"
type = "function"
uid = "fbce1275-45a6-5d58-181e-e9cbadf90b972e00cc37"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/cart_payment_methods_transform_run.graphql"
  export = "cart-payment-methods-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
